-- create "company" table
CREATE TABLE "company" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10), "name" text NOT NULL, "description" text NULL, "created" date NOT NULL, "updated" date NOT NULL, "active" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"));
-- create "job" table
CREATE TABLE "job" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10), "company_id" integer NOT NULL, "original_url" text NULL, "description" text NULL, "requirements" text NULL, "benefits" text NULL, "created" date NOT NULL, "updated" date NOT NULL, "active" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"), CONSTRAINT "company_id" FOREIGN KEY ("company_id") REFERENCES "company" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "publication" table
CREATE TABLE "publication" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10), "job_id" integer NOT NULL, "comment" text NULL, "started" date NOT NULL, "ended" date NOT NULL, "created" date NOT NULL, "updated" date NOT NULL, "active" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"), CONSTRAINT "job_id" FOREIGN KEY ("job_id") REFERENCES "job" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "scrap_log" table
CREATE TABLE "scrap_log" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10), "job_id" integer NOT NULL, "comment" text NULL, "original_url" text NOT NULL, "created" date NOT NULL, "result" smallint NOT NULL, "found" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"), CONSTRAINT "job_id" FOREIGN KEY ("job_id") REFERENCES "job" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "archive" table
CREATE TABLE "archive" ("id" integer NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10), "job_id" integer NOT NULL, "comment" text NULL, "original_url" text NULL, "started" date NOT NULL, "ended" date NOT NULL, "created" date NOT NULL, "updated" date NOT NULL, "active" boolean NOT NULL DEFAULT true, PRIMARY KEY ("id"), CONSTRAINT "job_id" FOREIGN KEY ("job_id") REFERENCES "job" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
